#!/bin/bash
# $1 is the reponse id
URL="http://localhost:$1/$2"
status=404
echo "Wait while not started"
while [ $status -eq 404 ]; 
do
    status=$(curl -w "%{http_code}\\n" -H "Accept:application/json" -H "Content-Type:application/x-www-form-urlencoded" $URL -s -o body)
    echo "STATUS:" $status
    echo -n "BODY:"
    cat body
    echo
done
echo "Wait while in progress"
while [ $status -eq 202 ]; 
do
    status=$(curl -w "%{http_code}\\n" -H "Accept:application/json" -H "Content-Type:application/x-www-form-urlencoded" $URL -s -o body)
    echo "STATUS:" $status
    echo -n "BODY:"
    cat body
done

echo "Check that it is gone"
status=$(curl -w "%{http_code}\\n" -H "Accept:application/json" -H "Content-Type:application/x-www-form-urlencoded" $URL -s -o body)
echo "STATUS:" $status
echo -n "BODY:"
cat body


