#!/bin/bash
# $1 is the reponse id
URL="http://localhost:$1/$2"
status=$(curl -w "%{http_code}\\n" -H "Accept:application/json" -H "Content-Type:application/x-www-form-urlencoded" --data "bad=monkey" $URL -s -o body)
echo "STATUS:" $status
echo -n "BODY:"
cat body
echo
