#!/bin/bash
URL="http://localhost:$1/shutdown"
status=$(curl -w "%{http_code}\\n" -H "Accept:application/json" -H "Content-Type:application/x-www-form-urlencoded" $URL -s -o body)
echo "STATUS:" $status
echo -n "BODY:"
cat body
echo

