#!/bin/bash
URL="http://localhost:$1/stats"
status=$(curl -w "%{http_code}\\n" -H "Accept:application/json" -H "Content-Type:application/x-www-form-urlencoded" $URL -s -o statbody)
echo "STATUS:" $status
echo -n "BODY:"
cat statbody
echo
